"""empty message

Revision ID: d3b45328117f
Revises: 
Create Date: 2019-11-04 00:05:02.614903

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'd3b45328117f'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('server')
    op.drop_table('projects')
    op.drop_table('testtable')
    op.drop_table('updating')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('updating',
    sa.Column('id', sa.INTEGER(), nullable=False),
    sa.Column('project_id', sa.INTEGER(), nullable=True),
    sa.Column('project_name', sa.VARCHAR(), nullable=True),
    sa.Column('version', sa.VARCHAR(), nullable=True),
    sa.Column('updating_type', sa.VARCHAR(), nullable=True),
    sa.Column('created_time', sa.VARCHAR(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('testtable',
    sa.Column('id', sa.INTEGER(), nullable=False),
    sa.Column('project_id', sa.INTEGER(), nullable=True),
    sa.Column('project_name', sa.VARCHAR(), nullable=True),
    sa.Column('version', sa.VARCHAR(), nullable=True),
    sa.Column('updating_type', sa.VARCHAR(), nullable=True),
    sa.Column('created_time', sa.VARCHAR(), nullable=True),
    sa.Column('newer', sa.VARCHAR(), nullable=True),
    sa.ForeignKeyConstraint(['project_id'], ['projects.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('projects',
    sa.Column('id', sa.INTEGER(), nullable=False),
    sa.Column('name', sa.VARCHAR(), nullable=True),
    sa.Column('version', sa.VARCHAR(), nullable=True),
    sa.Column('server', sa.VARCHAR(), nullable=True),
    sa.Column('data_path', sa.VARCHAR(), nullable=True),
    sa.Column('config_file_path', sa.VARCHAR(), nullable=True),
    sa.Column('source_code_path', sa.VARCHAR(), nullable=True),
    sa.Column('created_time', sa.VARCHAR(), nullable=True),
    sa.Column('updated_time', sa.VARCHAR(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('server',
    sa.Column('id', sa.INTEGER(), nullable=False),
    sa.Column('name', sa.VARCHAR(), nullable=True),
    sa.Column('super_secret', sa.VARCHAR(), nullable=True),
    sa.Column('created_time', sa.VARCHAR(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###
