# Generated by Django 2.2.6 on 2019-12-05 18:42

import codeshipper_app.models.updating
from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Project',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=50)),
                ('code', models.CharField(max_length=50, unique=True)),
                ('type', models.IntegerField(blank=True, null=True)),
                ('config_path', models.CharField(default='', max_length=100)),
                ('config_service', models.TextField(default='', max_length=50)),
                ('script_deploy', models.TextField(default='', max_length=50)),
                ('version', models.CharField(default='', max_length=50)),
                ('note', models.TextField(default='', max_length=50)),
                ('created_time', models.DateTimeField(default=django.utils.timezone.now)),
                ('updated_time', models.DateTimeField(default=django.utils.timezone.now)),
            ],
        ),
        migrations.CreateModel(
            name='ProjectType',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=50)),
                ('configuration', models.TextField(default='')),
                ('script', models.TextField(default='')),
                ('created_time', models.DateTimeField(default=django.utils.timezone.now)),
                ('updated_time', models.DateTimeField(default=django.utils.timezone.now)),
            ],
        ),
        migrations.CreateModel(
            name='Role',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('user_id', models.IntegerField()),
                ('user_name', models.CharField(max_length=50)),
                ('server_id', models.IntegerField()),
                ('server_name', models.CharField(max_length=50)),
                ('created_time', models.DateTimeField(default=django.utils.timezone.now)),
                ('updated_time', models.DateTimeField(default=django.utils.timezone.now)),
            ],
        ),
        migrations.CreateModel(
            name='Server',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=50)),
                ('port', models.IntegerField()),
                ('secret', models.CharField(max_length=50)),
                ('note', models.TextField()),
                ('created_time', models.DateTimeField(default=django.utils.timezone.now)),
                ('updated_time', models.DateTimeField(default=django.utils.timezone.now)),
            ],
        ),
        migrations.CreateModel(
            name='Updating',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('project_name', models.CharField(default='', max_length=50)),
                ('project_version', models.CharField(default='', max_length=50, unique=True)),
                ('server_host', models.CharField(default='', max_length=100)),
                ('deploy_type', models.CharField(default='', max_length=50)),
                ('deploy_time', models.DateTimeField()),
                ('updating_type', models.CharField(default='', max_length=50)),
                ('source_code_path', models.CharField(default='', max_length=100)),
                ('config_path', models.CharField(default='', max_length=100)),
                ('config_service', models.CharField(default='', max_length=50)),
                ('deploy_script', models.CharField(default='', max_length=50)),
                ('note', models.TextField(default='')),
                ('rollback', models.BooleanField(default=True)),
                ('state', models.CharField(default='undefined', max_length=50)),
                ('output', models.TextField(default='')),
                ('created_time', models.DateTimeField(default=django.utils.timezone.now)),
                ('updated_time', models.DateTimeField(default=django.utils.timezone.now)),
                ('project_id', models.ForeignKey(on_delete=models.SET(codeshipper_app.models.updating.Updating.on_delete_project), to='codeshipper_app.Project')),
                ('server_id', models.ForeignKey(default='', on_delete=models.SET(codeshipper_app.models.updating.Updating.on_delete_server), to='codeshipper_app.Server')),
            ],
        ),
    ]
