# Generated by Django 2.2.6 on 2019-11-18 16:57

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('codeshipper_app', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='server',
            old_name='super_secret',
            new_name='secret',
        ),
    ]
