# Generated by Django 2.2.6 on 2019-11-20 21:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('codeshipper_app', '0002_auto_20191118_1657'),
    ]

    operations = [
        migrations.AddField(
            model_name='project',
            name='config_service',
            field=models.CharField(default='', max_length=50),
        ),
        migrations.AddField(
            model_name='project',
            name='note',
            field=models.TextField(default='', max_length=50),
        ),
        migrations.AddField(
            model_name='project',
            name='script_deploy',
            field=models.CharField(default='', max_length=50),
        ),
        migrations.AddField(
            model_name='project',
            name='type',
            field=models.CharField(default='', max_length=50),
        ),
        migrations.AddField(
            model_name='project',
            name='variables',
            field=models.CharField(default='', max_length=50),
        ),
        migrations.AlterField(
            model_name='project',
            name='version',
            field=models.CharField(default='', max_length=50),
        ),
    ]
