# Generated by Django 2.2.6 on 2019-11-20 21:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('codeshipper_app', '0003_auto_20191120_2154'),
    ]

    operations = [
        migrations.AlterField(
            model_name='project',
            name='code',
            field=models.CharField(max_length=50, unique=True),
        ),
    ]
